### ISSUE TITLE
Use protoeasy within Docker

### ISSUE THREAD

**Issue by bufdev** [marcuswestin/go-birect#1]
Hey,

Thanks for using protoeasy, hope it is working ok for you! I saw you are still installing protoc, an FYI that you could change this to:

go get -v go.pedge.io/protoeasy/cmd/protoeasy
docker pull quay.io/pedge/protoeasy
docker run --rm -p 6789:6789 quay.io/pedge.protoeasy
PROTOEASY_ADDRESS=$(DOCKER_IP):6789 protoeasy --go ...

And there would be no more need to install protobuf locally.

https://github.com/peter-edge/protoeasy-go#quick-start
https://github.com/peter-edge/protoeasy-go#clientserver-setup

If you want, I can send over a PR for this.

**Comment by marcuswestin** [comment]
Hi! Thanks for the note - and for protoeasy, which I think is a great tool!

As for the suggested patch, I much prefer a one-time slow build over the additional docker installation requirement (minor inconvenience) and docker container running in the background (bigger inconvenience/source of complexity).

The solution I'd most prefer to see is a binary installation of protoc made available on e.g brew.

Cheers!
